<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #000;
            line-height: 1.5;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #000;
        }

        .header img {
            width: 110px;
            height: auto;
            margin-bottom: 8px;
        }

        h2 {
            margin: 0;
            font-size: 16px;
        }

        h3 {
            margin: 3px 0;
            font-size: 13px;
            font-weight: normal;
        }

        .meta {
            font-size: 11px;
            margin-top: 5px;
        }

        .section {
            margin-top: 15px;
        }

        .info {
            margin-bottom: 6px;
        }

        .message {
            margin-top: 15px;
            text-align: justify;
        }

        .signature {
            margin-top: 40px;
        }

        .signature img {
            width: 180px;
            height: auto;
            margin-bottom: 5px;
        }

        .signature p {
            margin: 3px 0;
        }

        .received {
            margin-top: 25px;
            border-top: 1px solid #000;
            padding-top: 10px;
        }

        .note {
            margin-top: 40px;
            font-size: 10px;
            font-style: italic;
            text-align: center;
        }
    </style>
</head>

<body>

<div class="header">

    <img src="{{ public_path('images/pagk_logo.png') }}" alt="Logo">

    <h2>PENTECOSTAL ASSEMBLIES OF GOD KENYA CHURCH</h2>

    <h3>HEADQUARTERS</h3>

    <div class="meta">
        P.O. Box 671-40100, Kisumu, Kenya
    </div>

</div>

<div class="section">

    <p class="info"><strong>Date:</strong> {{ now()->format('d M Y') }}</p>

    <p class="info"><strong>Pastor:</strong> {{ $transfer->pastor->name ?? '' }}</p>

    <p class="info">
        <strong>From:</strong>
        {{ $transfer->fromDistrict->name ?? '' }} /
        {{ $transfer->fromAssembly->name ?? '' }}
    </p>

    <p class="info">
        <strong>To:</strong>
        {{ $transfer->toDistrict->name ?? '' }} /
        {{ $transfer->toAssembly->name ?? '' }}
    </p>

</div>

<div class="message">

    <p>Dear {{ $transfer->toAssembly->name ?? 'Target Church' }},</p>

    <p>Calvary greetings from the Pentecostal Assemblies of God Headquarters.</p>

    <p>
        We kindly request you to receive <strong>{{ $transfer->pastor->name ?? '' }}</strong>,
        who has been officially transferred to your assembly. We trust that you will warmly
        welcome him/her and extend all necessary support as he/she begins ministry among you.
    </p>

    <p>
        Kindly accord him/her the cooperation, encouragement, and assistance needed to effectively
        serve the congregation and advance God’s work in your midst.
    </p>

    <p>May the Lord bless you abundantly as you receive and partner together in ministry.</p>

    <p>Yours in Christ,</p>

</div>

{{-- SYSTEM GENERATED SIGNATURE --}}
<div class="signature">

    <img src="{{ public_path('images/signatures/general_superintendent.jpg') }}"
         alt="Signature">

    <p><strong>Rev. Kenneth Adiara Mbalanya</strong></p>
    <p>General Superintendent</p>
    <p>PAG - K Church</p>

</div>

{{-- RECEIVED BY OVERSEER (NOW IMMEDIATELY AFTER SIGNATURE) --}}
<div class="received">
    <p><strong>Received by Overseer (Target):</strong> ____________________________</p>
    <p><strong>Date:</strong> ____________________________</p>
</div>

{{-- FOOTER NOTE (MOVED TO BOTTOM) --}}
<div class="note">
    This document was electronically generated by PAG Kenya Church Management System.
</div>

</body>
</html>